### ISSUE TITLE
Citation and Sources duplication

### ISSUE THREAD

**Issue by rufuspollock** [kiliakis/co2-ppm-ice-core#2]
I would not have Sources in README - have in the datapackage.json if necessary (though that should focus more on the original source data file).

I would suggest just having the citation. I would also put that as a `###` h3 section under the main License section.

See http://data.okfn.org/doc/publish-faq#readme for more details

**Comment by kiliakis** [comment]
@rgrp I fixed the Sources and Citation issues. Please review.
