### ISSUE TITLE
Add a graph

### ISSUE THREAD

**Issue by rufuspollock** [kiliakis/co2-ppm-ice-core#3]
Note: we do not really document this properly atm - something we need to do :-)

Best way is to copy and modify - see e.g. https://github.com/datasets/finance-vix/blob/master/datapackage.json#L48

**Comment by kiliakis** [comment]
@rgrp done with the graph

**Comment by rufuspollock** [comment]
@kiliakis great - can you link to the viewer so i can see it ;-) - and then you can close ...

**Comment by kiliakis** [comment]
@rgrp here is the link: http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fkiliakis%2Fco2-ppm-ice-core
I am closing the issue ;-)
